#!/usr/bin/env bash

echo ''
echo '###########################'
echo '# Finishing Project Setup #'
echo '###########################'
echo ''

echo '################################'
echo '# Install App Dev Dependencies #'
echo '################################'
echo ''
pipenv install --dev

echo ''
echo '##################################'
echo '# Install Invoke Bash Completion #'
echo '##################################'
echo ''
pipenv run ./invoke_bash_completion
rm -f invoke_bash_completion

echo '#############################################'
echo '# Initialize Git repo and make first commit #'
echo '#############################################'
echo ''
git init
git add .
git reset finish_project_setup
git commit -m 'Big Bang!' -m 'Project started using Cookiecutter: https://github.com/RTBHOUSE/big-bang-py'

echo ''
echo '###########################################'
echo '# Install and trigger pre-commit Git-hook #'
echo '###########################################'
rm -- "$0"  # Remove the current script to have clean
            # git working tree during pre-commit.
            # https://stackoverflow.com/a/8981233
pipenv run invoke install-precommit
pipenv run git commit

echo ''
echo '#####################################'
echo '# Load Pipenv shell for the project #'
echo '#####################################'
echo ''
pipenv shell
