#!/usr/bin/env bash

echo ''
echo '###########################################'
echo '# Remove this script to clean project dir #'
echo '###########################################'
echo ''
rm -- "$0"  # https://stackoverflow.com/a/8981233

echo '#########################################'
echo '# Install dev-dependencies using Pipenv #'
echo '#########################################'
echo ''
pipenv run pip install pip==18.0  # Pipenv bug... https://github.com/pypa/pipenv/issues/2871
pipenv install --dev

echo ''
echo '###############################################'
echo '# Initialize Git repo and create first commit #'
echo '###############################################'
echo ''
git init
git add .
git reset finish_project_setup
git commit -m 'Big Bang!' -m 'Project started using Cookiecutter: https://github.com/RTBHOUSE/big-bang-py'

echo ''
echo '###########################################'
echo '# Install and trigger pre-commit Git hook #'
echo '###########################################'
pipenv run invoke githooks.set-precommit
pipenv run git commit

echo ''
echo '#####################################'
echo '# Load Pipenv shell for the project #'
echo '#####################################'
echo ''
pipenv shell
