#!/usr/bin/env bash

echo ''
echo '############################'
echo '# Install dev-dependencies #'
echo '############################'
echo ''
invoke dependencies.compile
invoke dependencies.sync-dev

echo '###############################################'
echo '# Initialize Git repo and create first commit #'
echo '###############################################'
echo ''
git init
git add .
git reset finish_project_setup
git reset invoke_bash_completion
git commit -m 'Big Bang!' -m 'Project started using Cookiecutter: https://github.com/RTBHOUSE/big-bang-py'

echo ''
echo '###########################################'
echo '# Install and trigger pre-commit Git hook #'
echo '###########################################'
invoke set-precommit
.git/hooks/pre-commit

echo ''
echo '#######################################'
echo '# Scripts Auto-Destruction Activated! # '
echo '#######################################'
echo ''
rm -- "$0"  # https://stackoverflow.com/a/8981233
echo 'finish_project_setup... BOOM! GONE!'
rm ./invoke_bash_completion
echo 'invoke_bash_completion... BOOM! GONE!'

echo ''
echo '#######################################'
echo '# You are good to go! Happy coding :) # '
echo '#######################################'
echo ''
