#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Make Invoke-bash-tab-completion automatically sourced by virtualenv.
"""

import subprocess

from {{ cookiecutter.project_source_code_dir }}.utils import cowsay

virtual_env_activate_script_path = f"venv/bin/activate"
invoke_bash_completion_script_path = f"venv/bin/invoke_bash_completion_script"

completion_script_activated = False
with open(virtual_env_activate_script_path) as script:
    for line in script:
        if f"source {invoke_bash_completion_script_path}" in line:
            completion_script_activated = True
            break

if not completion_script_activated:
    subprocess.run(
        f"invoke --print-completion-script=bash > {invoke_bash_completion_script_path}",
        shell=True,
    )
    subprocess.run(
        f"echo 'source {invoke_bash_completion_script_path}' "
        f">> {virtual_env_activate_script_path}",
        shell=True,
    )
    cowsay("Invoke Bash tab-completion was installed in the virtualenv.")
