#!/usr/bin/env python3

import sys  # isort:skip
sys.path.insert(0, '.')  # yapf: disable

import time

from ci.ci_checks import run_ci_checks
from {{ cookiecutter.project_source_code_dir }}.utils import cowsay, humanize_seconds


def run_precommit():
    start_time = time.perf_counter()

    run_ci_checks()

    end_time = time.perf_counter()
    cowsay(f'Pre-commit execution time: {humanize_seconds(end_time - start_time)}')


if __name__ == '__main__':
    run_precommit()
