#!/usr/bin/env python3

import subprocess
import sys

from flake8.main import git
from isort.hooks import git_hook as isort_githook

if __name__ == '__main__':
    print('')
    print('#############')
    print('# Run tests #')
    print('#############')
    print('')
    tests_return_code = subprocess.run(['invoke', 'tests']).returncode
    # Exit code 0:	All tests were collected and passed successfully
    # Exit code 5:	No tests were collected
    if tests_return_code not in {0, 5}:
        print('')
        print(f'Tests Exit Status: {tests_return_code} => aborting commit!')
        sys.exit(tests_return_code)

    print('')
    print('###########################')
    print('# Dependency Safety Check #')
    print('###########################')
    print('')
    print('Scan your dependency graph for known security vulnerabilities!')
    print('')
    print('See below for further information:')
    print('⚔️  https://github.com/pypa/pipenv/blob/master/docs/advanced.rst#-detection-of-security-vulnerabilities')  # yapf: disable
    print('⚔️  https://github.com/pyupio/safety-db')
    print('')
    subprocess.run(['pipenv', 'check'])

    print('')
    print('######################')
    print('# Import Order Check #')
    print('######################')
    print('')
    isort_exit_status = isort_githook(strict=True)
    if isort_exit_status == 0:
        print('Isort Exit Status: 0 => OK!')
    else:
        sys.exit(isort_exit_status)

    print('')
    print('################################')
    print('# Code Formatting Check (YAPF) #')
    print('################################')
    print('')
    yapf_return_code = subprocess.run(['yapf', '--recursive', '--diff', '.']).returncode
    if yapf_return_code == 0:
        print('YAPF Exit Status: 0 => OK!')
    else:
        print('')
        print(f'YAPF Exit Status: {yapf_return_code} => aborting commit!')
        print('')
        sys.exit(yapf_return_code)

    print('')
    print('##################################')
    print('# Flake8 Style Guide Enforcement #')
    print('##################################')
    print('')
    flake8_return_code = git.hook(
        strict=git.config_for('strict'),
        lazy=git.config_for('lazy'),
    )
    if flake8_return_code == 0:
        print('Flake8 Exit Status: 0 => OK!')
        print('')
    else:
        print('')
        print(f'Flake8 Exit Status: {flake8_return_code} => aborting commit!')
        print('')
        sys.exit(flake8_return_code)
